default:
	mkfldhdr32 friend.fml
	cp friend.fml.h /home/oracle/tuxedo11gR1/include/friendfml.h
	rm friend.fml.h
	viewc32 -d $$TUXDIR/udataobj friend.v
	cp friend.h /home/oracle/tuxedo11gR1/include/
	rm friend.h
