default:
	viewc32 -d $$TUXDIR/udataobj friend.v
	cp friend.h $$TUXDIR/include/
	rm friend.h
	cp friend.fml $$TUXDIR/udataobj/
	mkfldhdr32 $$TUXDIR/udataobj/friend.fml
	cp friend.fml.h $$TUXDIR/include/friendfml.h
	rm friend.fml.h
